#+TITLE: ahrjarrett.com
#+AUTHOR: Andrew Jarrett <ahrjarrett@gmail.com>


* AWS

** Amplify CLI

Assuming your IAM user is created and the Amplify CLI is installed:

- New project: =amplify init=
- Make =aws-exports.js=, build all your local backend resources & provision it: =amplify push=
- Deploy: =amplify publish= (creates an S3 bucket in our account and uses Route 53 for hosting)
- Invalidate cache when publishing: =amplify publish -c=
- Status, get URL
  =amplify status=

  
*** Route 53
- New hosting:
  =amplify add hosting=

  
**** Hosted Zones

"A hosted zone is a container for records, and records contain information about how you want to route traffic for a specific domain, such as example.com, and its subdomains (acme.example.com, zenith.example.com). A hosted zone and the corresponding domain have the same name." [[https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/hosted-zones-working-with.html][Route 53 Docs on Hosted Zones]]

- When you register a domain with Route 53, we create a hosted zone for you automatically.

- In both cases, you then create records in the hosted zone to specify how you want to route traffic for the domain and subdomains. [[https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/AboutHZWorkingWith.html][Working with Records]]





*** CloudFront
To update your hosting to use (or not use) CloudFront run:

=amplify configure hosting=

**** SSL Configuration

We use the AWS Certificate Manager to create a certificate that points to our Hosted Zones.

Then we have to update our CloudFront config to use that certificate, instead of the one provided.

**** HSTS

/This part is necessary for .dev domains!/

If you want Cloudfront to handle custom security headers (like HSTS), you need to use a Lambda Edge function.

Guide:
https://aws.amazon.com/blogs/networking-and-content-delivery/adding-http-security-headers-using-lambdaedge-and-amazon-cloudfront/

Lambda Role:
cognito704b3e59_userpoolclient_lambda_role-dev


* DNS

** Point domain to bucket
[[https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html][Here's how we do that]]


** Point Google Domain

/Basically:/

- Make sure the bucket is set up to serve a static site
- Create a hosted zones with records that point to our S3 bucket (or in our case, our CloudFront CDN)
  
[[https://medium.com/@limichelle21/connecting-google-domains-to-amazon-s3-d0d9da467650][Medium article about it]]






