#+TITLE: README: Gatsby Org-Mode Blog
#+AUTHOR: Andrew Jarrett <ahrjarrett@gmail.com>
#+DATE: <2019-03-13 Wed>
#+TAGS: @documentation @graphql

Gatsby blog with org-mode rendering.

- [[https://github.com/ahrjarrett/ahrjarrett.com/tree/master/packages/blog][Repo]] (part of the ahrjarrett monorepo)
- [[https://xiaoxinghu.github.io/orgajs/docs/generate-static-website-with-gatsby][gatsby-orga docs]]
  

* TODO
- [ ] Deploy

* Config

Currently using orga to create an AST and my own package to take that AST and recursively build a tree of React components from it (~@ahrjarrett/org-mode~).

Also using ~@mosch/gatsby-source-github~ to pull down org files from my repo https://github.com/ahrjarrett/ahrjarrett.com using this GraphQL query:

#+BEGIN_SRC 
{
  allGithubFile(
    filter: {
      relativePath: { regex: "/^(packages/data/src/org/).+(.org)$/" }
    }
  ) {
    edges {
      node {
      base
    }
  }
}
#+END_SRC

* Dynamic search of org files?

This is interesting:

/gatsby-transformer-orga plugin provides 2 ways to generate your content from your org-mode source files/

1. one document per org-mode file
2. one document per section (sub-tree)

#+BEGIN_QUOTE
The former is the default option. To enable section based generation, add ORGA_PUBLISH_KEYWORD to your org file, and sections with matching keyword will be transformed into a standalone document. E.g.
#+END_QUOTE

Which looks like this in the org file:

#+BEGIN_SRC 
  ,#+ORGA_PUBLISH_KEYWORD: DONE

     ,* DONE My First Post
       CLOSED: [2018-12-14 Fri 15:44]

       ...

     ,* TODO A Draft
#+END_SRC


